import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import AuthInitializer from "./components/Sections/AuthIntialiser";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
  weight: "400",
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} antialiased`}>
        <AuthInitializer />
        {children}
      </body>
    </html>
  );
}
